# See PEP 518: https://www.python.org/dev/peps/pep-0518/ for info on this file's structure.

[tool.pyflow]
name = "bga"
py_version = "3.7"
version = "0.1.0"

[tool.pyflow.scripts]

[tool.pyflow.dependencies]
# core
# bgap = "^0.1.0"
python-clean-architecture = "^0.0.6"
parsel = "1.6.0"
ruia = {version = "~0.6.7", extras=["uvloop"]}
blinker = "1.4"
click = "7.1.2"
python-path = "0.1.3"
"ruamel.yaml" = "0.16.10"
# devops tools
pip = "~20.1.1"
setuptools = "~47.1.1"
wheel = "~0.34.2"
pytest-flake8 = "^1.0.6"
mock = "^4.0.2"

[tool.pyflow.dev-dependencies]
